version: '3'
services:
  pg:
    image: library/postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    environment:
      RAILS_ENV: development
      PG_USERNAME: postgres
      PG_PASSWORD: password
      PG_HOST: pg
      PG_PORT: 5432
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - pg
    volumes:
      - .:/app
      - myapp_bundle:/app/vendor/bundle
      - myapp_node_modules:/app/node_modules

volumes:
  pg-data:
    driver: local
  myapp_bundle:
    driver: local
  myapp_node_modules:
    driver: local
