name: Ruby

on:
  pull_request:
    branches:
    - master

jobs:
  run_spec:
    name: Run spec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: <%= ENV["PG_USERNAME"] %>
          POSTGRES_PASSWORD: <%= ENV["PG_PASSWORD"] %>
          POSTGRES_DB: medicine_pet_development
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5  
    steps:
    # actions/checkoutリポジトリのaction.ymlを利用する
    - uses: actions/checkout@v1 # https://github.com/actions/checkout/blob/master/action.yml
        # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsuses
        #   @~でバージョンやブランチ、コミットIDを指定できる
        #   自リポジトリのaction.ymlがあるディレクトリを相対パスで指定することもできる
        #     ex. uses: ./.github/actions/my-action
        #   Dockerhubのイメージを利用することもできる
        #     ex. uses: docker://alpine:3.8
    - name: Set up Ruby 3.0.2
      # actions/checkoutリポジトリのaction.ymlを利用する
      uses: actions/setup-ruby@v1 # https://github.com/actions/setup-ruby/blob/master/action.yml
      with:
        ruby-version: 3.0.2
    - name: yarn install
      run: yarn install --check-files
    
    - name: Test with Rspec
      run: |
        gem install bundler
        bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
        bundle exec rspec