name: Ruby

# masterブランチへのPR時の実行
on:
  pull_request:
    branches:
    - master
    # ex.
    # # Trigger the workflow on push or pull request
    # on: [push, pull_request]
    # # Trigger the workflow on pull request activity
    # on:
    #   release
    #     # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    #     types: [published, created, edited]

jobs:
  run_spec:
    name: Run spec

    # ジョブを実行する仮想マシンを選択（ubuntu/macOS/Windows)
    runs-on: ubuntu-latest

    steps:
    # actions/checkoutリポジトリのaction.ymlを利用する
    - uses: actions/checkout@v1 # https://github.com/actions/checkout/blob/master/action.yml
        # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsuses
        #   @~でバージョンやブランチ、コミットIDを指定できる
        #   自リポジトリのaction.ymlがあるディレクトリを相対パスで指定することもできる
        #     ex. uses: ./.github/actions/my-action
        #   Dockerhubのイメージを利用することもできる
        #     ex. uses: docker://alpine:3.8
    - name: Set up Ruby 3.0.2
      # actions/checkoutリポジトリのaction.ymlを利用する
      uses: actions/setup-ruby@v1 # https://github.com/actions/setup-ruby/blob/master/action.yml
      with:
        ruby-version: 3.0.2
    - name: Test with Rspec
      run: |
        gem install bundler
        bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
        bundle exec rspec